version: '3.7'

services:
  sdspopenapi:
    container_name: sdsp-openapi
    restart: unless-stopped
    image: sdsp-openapi:latest
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /data/sdsp/netcdf/storage:/netcdf/storage/
      - /data/sdsp/netcdf/export:/netcdf/export/
    ports:
      - '4994:4994'

